<script lang="ts">
  import Button from '$lib/components/Button.svelte';
  import { ArrowRight, CheckCircle2, ClipboardCheck, FileText, ListTodo, Paperclip, Plus, ReceiptText, ShoppingCart, TriangleAlert, Wallet } from 'lucide-svelte';
  import { getContext } from 'svelte';
  import type { WorkspaceContext } from '$lib/workspace-context';
  import { WORKSPACE_CONTEXT } from '$lib/workspace-context';
  import { date, money, overdue, stageProgress, stageTone } from '$lib/workspace-utils';

  const workspace = getContext<WorkspaceContext>(WORKSPACE_CONTEXT);

</script>

<section><div class="page-head"><div><div class="eyebrow">PROCUREMENT · COST WRITEBACK</div><h1>采购与成本</h1><p>执行阶段在这里记录采购需求和物料成本。供应商报价建议至少 3 家；定标后会形成承诺成本并回写项目。</p></div><Button variant="primary" onclick={() => workspace.open('procurement')}> <Plus size={16} />新增采购需求</Button></div><div class="cost-guide"><span>预计成本 <b>{money(workspace.state.order!.cost_summary.find((item) => item.cost_type === '预计')?.amount)}</b></span><span>承诺成本 <b>{money(workspace.state.order!.cost_summary.find((item) => item.cost_type === '承诺')?.amount)}</b></span><span>实际成本 <b>{money(workspace.state.order!.actual_cost)}</b></span></div>{#each workspace.state.order!.procurement_items as item}<section class="panel section-gap"><div class="panel-head"><div><h2>{item.name}</h2><span>预算 {money(item.budget)} · 报价 {item.offers?.length ?? 0} 家{(item.offers?.length ?? 0) < 3 ? '（建议至少 3 家）' : ''}</span></div><span class="status-pill" class:green={item.status === '已定标'} class:orange={item.status !== '已定标'}>{item.status}</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>供应商</th><th>报价</th><th>预算差额</th><th>报价凭证</th><th>操作</th></tr></thead><tbody>{#each item.offers ?? [] as offer}<tr><td><b>{offer.supplier}</b></td><td>{money(offer.amount)}</td><td class:down={offer.amount > item.budget}>{offer.amount > item.budget ? '+' : ''}{money(offer.amount - item.budget)}</td><td>{offer.proof}</td><td>{#if item.status !== '已定标'}<Button size="sm" onclick={() => workspace.award(item, offer)}>选择并定标</Button>{:else}<span class="status-pill green">已定标</span>{/if}</td></tr>{:else}<tr><td colspan="5" class="empty">暂无供应商报价，请新增报价</td></tr>{/each}</tbody></table></div>{#if item.status !== '已定标'}<Button size="sm" onclick={() => workspace.open('offer', item)}><Plus size={14} />新增供应商报价</Button>{/if}</section>{/each}{#if !workspace.state.order!.procurement_items.length}<div class="guided-empty"><b>当前还没有采购需求</b><p>如项目需要外采，请先新增采购需求，再录入供应商报价并完成定标。定标后才会形成承诺成本。</p><Button onclick={() => workspace.open('procurement')}><Plus size={14} />新增采购需求</Button></div>{/if}</section>
